# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RSVP-Server

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.REGESTRY_USERNAME }}
        password: ${{ secrets.REGESTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RSVP-Server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_40a67e3e7eeb40409048d9cefe1b182a }}
        images: 'mcr.microsoft.com/${{ secrets.REGESTRY_USERNAME }}/appsvc/staticsite:${{ github.sha }}'
